### ISSUE TITLE
update the game instead of making an useless anti cheat for it

### ISSUE THREAD

**Issue by enescglyn** [Hexcede/Dato-Issues#4]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [you add anti saveinstance but there is no asset to be stolen in your game]

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Hexcede** [comment]
Please fill in the format.
Most updates revolve around bug fixes/anticheat stuff right now because those are the things that are the quickest for me to publish, not because those are the only things I've been working on.
